[project]
name = "joupro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.22.1",
    "asyncpg>=0.31.0",
    "cloudinary>=1.45.0",
    "fastapi>=0.139.2",
    "fastapi-users[sqlalchemy]>=15.0.5",
    "imagekitio>=5.8.0",
    "psycopg2-binary>=2.9.13",
    "python-dotenv>=1.2.2",
    "uvicorn[standard]>=0.51.0",
    "langchain-tavily",
    "langgraph",
    "langchain-groq",
]
